// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package ipsec

import (
	"context"
	"github.com/browningluke/opnsense-go/pkg/api"
)

var ServiceOpts = api.ReqOpts{
	AddEndpoint:         "",
	GetEndpoint:         "/api/ipsec/service/status",
	UpdateEndpoint:      "",
	DeleteEndpoint:      "",
	ReconfigureEndpoint: ipsecReconfigureEndpoint,
	Monad:               "Service",
}

// Data structs

type Service struct {
	Status  string `json:"status"`
	Running bool   `json:"running"`
}

// CRUD operations

func (c *Controller) GetService(ctx context.Context, id string) (*Service, error) {
	return api.Get(c.Client(), ctx, ServiceOpts, &Service{}, id)
}

func (c *Controller) GetServiceAll(ctx context.Context) ([]Service, error) {
	return api.GetAll(c.Client(), ctx, ServiceOpts, []Service{})
}
